#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout float
yabai -m config window_border on
yabai -m config active_window_border_color 0xff2c9678
yabai -m config normal_window_border_color 0x002E3440
yabai -m config insert_feedback_color 0xFFA3BE8C

echo "yabai configuration loaded.."

#END
